### PR TITLE
RPC logging improvements

### LINKED ISSUE #19: RPC logging improvements.
Currently we log RPC requests at level `DEBUG` with full request/response objects.

We need logging at level `INFO` that shows the calls being made and the types of arguments and responses, without showing their values (and also #18)

The full request/response objects can still be logged at `DEBUG` level.

### PR DESCRIPTION
**Pull request by koden-km**
(fixes #19)

### CODE REVIEW

**Comment by jmalloc** [comment]
Have you brought this into fantasy or any of the other projects to try it out... see how it looks?

**Comment by koden-km** [comment]
Not yet. I'll try that on Monday.

**Comment by jmalloc** [comment]
Paste some examples here once you've given a go plsmang

**Comment by koden-km** [comment]
Example results.

Success:
```
2017-01-03 04:53:02 DEBG rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #28 request project/api/v1/listStuff(0, <stdClass @ 0000000073a3a36200000000029744a9>, <stdClass @ 0000000073a3a36c00000000029744a9>)
2017-01-03 04:53:05 DEBG rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #28 response project/api/v1/listStuff(0, <stdClass @ 0000000073a3a36200000000029744a9>, <stdClass @ 0000000073a3a36c00000000029744a9>) -> SUCCESS <stdClass @ 0000000073a3a08b00000000029744a9>
2017-01-03 04:53:05 INFO rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #28 project/api/v1/listStuff -> SUCCESS
```

Failure:
```
2017-01-03 04:53:46 DEBG rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #32 request project/api/v1/createThing(0, <stdClass @ 0000000073a3a0d200000000029744a9>)
2017-01-03 04:53:46 DEBG rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #32 response project/api/v1/createThing(0, <stdClass @ 0000000073a3a0d200000000029744a9>) -> EXCEPTION "Invalid arguments, missing: name."
2017-01-03 04:53:46 INFO rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #32 project/api/v1/createThing -> EXCEPTION
```

**Comment by jmalloc** [comment]
What do you think of this?

```
DEBG rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #28 REQUEST project/api/v1/listStuff(0, <stdClass @ 0000000073a3a36200000000029744a9>, <stdClass @ 0000000073a3a36c00000000029744a9>)
DEBG rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #28 RESPONSE project/api/v1/listStuff <stdClass @ 0000000073a3a08b00000000029744a9>
INFO rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #28 SUCCESS project/api/v1/listStuff
```

```
INFO rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #28 EXCEPTION project/api/v1/listStuff
```

**Comment by koden-km** [comment]
Here is some real results with those upper case words:

Success:
```
2017-01-04 02:30:43 DEBG rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #89 REQUEST project/api/v1/listStuff(0, <stdClass @ 000000002ae297b60000000065129382>, <stdClass @ 000000002ae2972a0000000065129382>)
2017-01-04 02:30:43 DEBG rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #89 RESPONSE project/api/v1/listStuff(0, <stdClass @ 000000002ae297b60000000065129382>, <stdClass @ 000000002ae2972a0000000065129382>) -> SUCCESS <stdClass @ 000000002ae297040000000065129382>
2017-01-04 02:30:43 INFO rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #89 SUCCESS project/api/v1/listStuff
```

Failure:
```
2017-01-04 02:31:03 DEBG rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #90 REQUEST project/api/v1/createThing(0, <stdClass @ 000000002ae297b50000000065129382>)
2017-01-04 02:31:03 DEBG rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #90 RESPONSE project/api/v1/createThing(0, <stdClass @ 000000002ae297b50000000065129382>) -> EXCEPTION "Invalid arguments, missing: name."
2017-01-04 02:31:03 INFO rpc.server amq.gen-HsH0rV5MUAQFq0FbVTIsQQ #90 EXCEPTION project/api/v1/createThing
```

**Comment by koden-km** [comment]
One issue now though, how does the client get the error reason message?

**Pull request merged**
